### ISSUE TITLE
Start website design

### ISSUE THREAD

**Issue by LayneY** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#21]
Create a design for the admin website for event creation and management, user management, etc.

**Comment by LayneY** [comment]
https://www.figma.com/file/bULuMB8ITO4VN4B1avR3F7/Eagle-Engagement-Admin?type=design&node-id=0%3A1&mode=design&t=z71oHFtPGlvnaxtE-1 @Logan-Rohlfs

**Comment by brett-k-cs** [comment]
- [x] Login Page
- [x] Signup Page - Restricted to @allenisd.org
- [x] Admin Area
  - [x] Add/Edit Location Page - Name, Address, Coordinates, Radius (using google maps api or open street maps)
  - [x] Add/Edit Event Page - Name, Type, Location Chooser
  - [x] "Request Missing Points" Responses Page - Easily link to the student / approve their request
  - [x] Review a student's dress-up days submission Page
  - [x] Review teacher's requests for adding events Page
- [x] Teacher / Club Sponsor Area
  - [x] Teacher Dashboard - See list of clubs they sponsor
  - [x] Club Page - See how many & which students attended latest meetings
  - [x] Request Club Event Page - request to be shown on the events page, need to provide necessary information (location)

**Comment by brett-k-cs** [comment]
![image](https://github.com/Allen-ISD-Computer-Science/REPO_EagleEngagement_2024/assets/89534091/1116f7e8-d46d-4dff-bd12-adea16368267)
Created new design
