### ISSUE TITLE
Discuss with Contact about Login

### ISSUE THREAD

**Issue by LayneY** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#23]
Once we have our contact we need to discuss:
- [ ] Database of emails to IDs
- [ ] Other possible ways of getting student IDs

**Comment by brett-k-cs** [comment]
We also need to discuss the actual authentication method. Google Login would be the best, but I'm not sure if we will get approval.

- [ ] Finalize (and describe) the authentication method.

**Comment by brett-k-cs** [comment]
Mr. BY said to use an email-verified login for now. We will be looking at Google Auth later down the road.

I am going to start the VAPOR code for it. We have updated the database schema file to include another table and a password hash field. 

Users will have to input their own student ID for now
