### ISSUE TITLE
Start routes for authentication.

### ISSUE THREAD

**Issue by brett-k-cs** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#34]
- [x] Create the routes to facilitate sign-in / sign-up
  - [x] Sign In
  - [x] Sign Up
- [x] Create a Manager / Controller on the backend to validate the faculty authentication (a token, cookie, etc.)

**Comment by brett-k-cs** [comment]
Authentication Table will only be necessary for Students as Teachers / Faculty can use cookies.

Sign In and Controller is done for Faculty. Need to do for students.

**Comment by captainbboy** [comment]
Made the Authentication Table unnecessary by adding an "expiredCount" to studentUser and forcing JWTs to match that to be valid.

**Comment by brett-k-cs** [comment]
Authentication Table's need removed entirely. Adding an "expirationCount" to studentUsers to facilitate same purpose ("log out of all devices")

**Comment by brett-k-cs** [comment]
Will continue this issue sprint 8
