### ISSUE TITLE
Get as many pages as possible imported to React.

### ISSUE THREAD

**Issue by Logan-Rohlfs** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#35]
- [x] Home Page
- [x] Sign-In Page
- [x] Setup Components
  - [x] Admin NavBar Component
  - [x] Teacher NavBar Component
- [x] Admin Pages
- [x] Teacher Pages

**Comment by brett-k-cs** [comment]
Didnt get to Admin Pages, will do next week

**Comment by brett-k-cs** [comment]
Using Material UI now as well
