### ISSUE TITLE
Start importing screens to android app using dhiwise

### ISSUE THREAD

**Issue by brett-k-cs** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#37]
- [x] SignIn Page
- [x] NavBar Component
- [x] Events Page
  - [ ] Event Component with proper constructor
- [x] Event Page with proper constructor
- [x] Profile Page
- [x] Clubs Page
  - [ ] Club Component with proper constructor
- [x] Club Page with proper constructor
- [x] Rewards Page
- [x] Point Request Page
- [x] Point History Page

**Comment by LayneY** [comment]
Used dhiwise to create XML files for each page. Plan to export to android studio next class. https://app.dhiwise.com/application/65a6c0ef2bb57f0023756c7c

**Comment by LayneY** [comment]
Will continue next week
