### ISSUE TITLE
Fix formatting for iOS pages

### ISSUE THREAD

**Issue by brett-k-cs** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#52]
- [x] Event list
- [x]  Event page
- [x]  Club list
- [x]  Club page
- [x]  Login pages
  - [x]  Sign up
  - [x]  Login
  - [x]  Password recovery
- [x]  Rewards list
- [x]  Reward page

**Comment by brett-k-cs** [comment]
Extended due to lack of hardware

**Comment by Logan-Rohlfs** [comment]
Extended to Sprint 15 for rest of the pages

**Comment by Logan-Rohlfs** [comment]
Extended to Sprint 16 for rest of the pages

**Comment by Logan-Rohlfs** [comment]
Closed on Completion
