### ISSUE TITLE
Design a graphical logo that still fits our current color scheme

### ISSUE THREAD

**Issue by brett-k-cs** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#63]
- [x] Find (similar) font to logo image
- [x] Create the graphic part of the logo
- [x] Create a few versions of the logo (with and without graphic) - one needs to be square

**Comment by Logan-Rohlfs** [comment]
Current Design Mockup from 2/14
* Need to make different types and sizes throughout pages


![Image](https://github.com/Allen-ISD-Computer-Science/REPO_EagleEngagement_2024/assets/92662751/ac55902c-826f-469a-a237-069dd48b0a75)

**Comment by brett-k-cs** [comment]
Complete - awaiting finals renders

**Comment by Logan-Rohlfs** [comment]
![Image](https://github.com/Allen-ISD-Computer-Science/REPO_EagleEngagement_2024/assets/92662751/a2089c13-f95e-46f2-ba96-e192bb585a7d)
![Image](https://github.com/Allen-ISD-Computer-Science/REPO_EagleEngagement_2024/assets/92662751/ff61deca-61ee-448d-894d-c9ae2e1afcb2)
![Image](https://github.com/Allen-ISD-Computer-Science/REPO_EagleEngagement_2024/assets/92662751/a1ea0c2d-ba37-409a-a358-310851b6a6a3)
