### ISSUE TITLE
Start Branding

### ISSUE THREAD

**Issue by brett-k-cs** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#7]
- [x] Pick Color Scheme (Assume we have to follow AHS?)
- [x] Design Logo

**Comment by Logan-Rohlfs** [comment]
Id assume color scheme would follow Red, White Blue of AHS branding and the logo could be some variation of the current logo of the Eagle Engagement app (assuming we get permission to reuse that logo.

**Comment by brett-k-cs** [comment]
Update to this, we went with a close color scheme to AHS, mainly focused on the blue and white colors. The hue of the blue was changed to make it less harsh on the eyes.

Logan also mostly replicated the current Eagle Engagement logo which we will use unless we are told there are copyright issues with it.

**Comment by LayneY** [comment]
Mr. Ben says "you do you" and says they can complain about the logo later.
