### ISSUE TITLE
Start mobile app design

### ISSUE THREAD

**Issue by LayneY** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#8]
- [x] Design a login page
- [x] Design a home page (show points, upcoming events, etc)
- [x] Design event page (details about event, points, date, location, etc)
- [x] Design rewards page

**Comment by brett-k-cs** [comment]
Some technology I think we should look into is using Figma for the design and then exporting it with "dhiwise". Found a cool video about it on youtube: https://www.youtube.com/watch?v=t7lUSiddFd4 (it also supports android/ios not just flutter)

This way it will be easier to export to both platforms with the exact same design

**Comment by brett-k-cs** [comment]
https://www.figma.com/file/qRGIIZMzdZQaYzVpQdvpYu/EagleEngagment?type=design&node-id=0%3A1&mode=design&t=JZajXGzLQt8rRYDg-1

**Comment by brett-k-cs** [comment]
@Logan-Rohlfs thoughts?
