### ISSUE TITLE
Investigate Push Notifications

### ISSUE THREAD

**Issue by LayneY** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#81]
Look at how push notifications work for iOS and Android and investigate how implementation for event alerts will work.

**Comment by LayneY** [comment]
Firebase has solutions for iOS and Android: https://firebase.google.com/docs/cloud-messaging

**Comment by brett-k-cs** [comment]
Firebase sending through Vapor: https://github.com/MihaelIsaev/FCM
