### ISSUE TITLE
Get in contact with the Client

### ISSUE THREAD

**Issue by brett-k-cs** [Allen-ISD-Computer-Science/REPO_EagleEngagement_2024#9]
Email the client to receive their feedback & adjust our features / plans based on it.

**Comment by LayneY** [comment]
Started writing draft to send to administrator

**Comment by LayneY** [comment]
Still waiting for Mr. Ben to tell us who to send it to.

**Comment by brett-k-cs** [comment]
sadge

**Comment by LayneY** [comment]
#antiminga
